name: Github Actions Setup

on: [push]

jobs:

  setup_job:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout del codigo
       uses: actions/checkout@v4

     - name: Ejecutando scripts de setup
       run: |
         echo "Iniciando fase de setpu..."
         echo "Preparando entorno de CI..."
         echo "Setup completado correctamente."
