name: Github Actions Setup
on: [push]
jobs:
  setup_job:
    runs-on: ubuntu-lastest
    steps:
      - name: Checkout del c√≥digo
      - uses: actions/checkout@v4
      - name: Ejecutando scripts de setup
        run: |
          echo "Iniciando fase de setpu..."
          echo "Preparando entorno de CI..."
          echo "Setup completado correctamente."
